# Introduction to Numpy and Scipy

- Pyhton: A programming language 


- If we want do further, we rely on Packages


- In the lecture today, you will learn Numpy and Scipy
---

## Numpy

- __Num__erical __Py__thon


- There are a lot useful functions in Numpy


- When we learn numpy, you will know ``Objective''


- We start from how to import package and learn ``'Array'

---

In [1]:
# Import Numpy

import numpy

In [2]:
numpy.log(1)

0.0

# Import Package

- In previouse case we use 

```Python
import numpy
```


- However, it could be too long

In [3]:
# Import Numpy in the name you prefer

import numpy as np

In [4]:
np.log(1)

0.0

# Import Package

- We know how to use shorter name to import numpy


- However, for some functions like, log or exp, we may use it a lot

- Therefore, type 

```python 
np.log(1)
``` 

is too long

In [7]:
# Direct import log from numpy

from numpy import log

In [8]:
log(1)

0.0

# Array

- In numpy, we have array. It's like vector in math


- It's very useful


- For example, you want to compute $$u(c) = c - c^2/2 $$

for $c = 0.1, 0.2, 0.3, 0.4$

In [10]:
def u(c):
    return c-c**2/2

In [11]:
xlist = [0.1, 0.2, 0.3, 0.4]

In [12]:
u(xlist)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [13]:
xarray = np.array(xlist)
xarray

array([0.1, 0.2, 0.3, 0.4])

In [14]:
u(xarray)

array([0.095, 0.18 , 0.255, 0.32 ])

In [4]:
x = 2
y = x**2 - 5*x + 1
y

-5

## Objective

- Array is belongs to numpy


- Therefore,  functions in numpy can be applied

In [8]:
x = np.array([2,3,4,5,6])
x

array([2, 3, 4, 5, 6])

In [9]:
np.mean(x)

4.0

In [10]:
x.mean()

4.0

In [11]:
np.max(x)

6

In [12]:
x.max()

6

# Scipy

- __Sci__entific Computation in __Py__thon


- Very similar to Numpy, but has more tools


- Solving simutaneous equations: ```fsolve```


- Find max or min: ```minimize```

In [15]:
from scipy.optimize import fsolve, minimize

## Ex1 

If you want to solve 

$$2\cdot x + y = 1$$
$$ x + y = 5 $$

Actually, we want to solve 

$$2\cdot x + y - 1 = 0$$
$$ x + y - 5 = 0 $$


In [16]:
def g(X):
    x = X[0]
    y = X[1]
    eq0 = 2*x + y - 1
    eq1 = x + y - 5
    return eq0, eq1

In [17]:
g([1,1])

(2, -3)

In [18]:
fsolve(g, [1,1])

array([-4.,  9.])

In [19]:
g([-4, 9])

(0, 0)

## Consumption and Saving 

We actually solve simutaneous equations 

$$ u'(c_t) = \beta (1+r_t) u'(c_{t+1}) $$


$$ c_t + \frac{c_{t+1}}{1+r_t} = Y_t + \frac{Y_{t+1}}{1+r_t} $$


- $\beta, r_t, Y_t, Y_{t+1}$ are exogenous 


- $c_t, c_{t+1}$: we want to find


- Given $u'(c) = \frac{1}{c}$


$$ \frac{1}{c_t} = \beta (1+r_t) \frac{1}{c_{t+1}}$$


$$ c_t + \frac{c_{t+1}}{1+r_t} = Y_t + \frac{Y_{t+1}}{1+r_t} $$


Actually, we find $c_t, c_{t+1}$ to satisfy 

$$ 1/c_t - \beta (1+r_t) (1/c_{t+1}) = 0 $$


$$ c_t + \frac{c_{t+1}}{1+r_t} - Y_t - \frac{Y_{t+1}}{1+r_t} = 0 $$


In [20]:
r = 0.05
bet = 1/(1+r)
Y0 = 50
Y1 = 100

def Eqs(C):
    c0 = C[0]
    c1 = C[1]
    eq0 = 1/c0 - bet*(1+r)/c1
    eq1 = c0 + c1/(1+r) - Y0 - Y1/(1+r)
    return eq0, eq1

In [23]:
Eqs([50, 100])

(0.01, 0.0)

In [24]:
fsolve(Eqs, [50, 100])

array([74.3902439, 74.3902439])

## Ex2: Max

Find the max for 

$$ f(x) = -x^2 + 3x + 1 $$

In [36]:
def f(x):
    return -x**2 + 3*x + 1

In [37]:
f(1)

3

In [38]:
f(1.2)

3.1599999999999997

## Finding max and min in Computer

- All comupter program only offer you the program to find min value


- With a minus sign for a function, you can use the program to get the max value

In [39]:
def f2(x):
    return -1*f(x)

In [40]:
minimize(f2, 1)

      fun: -3.25
 hess_inv: array([[0.49999999]])
      jac: array([0.])
  message: 'Optimization terminated successfully.'
     nfev: 12
      nit: 2
     njev: 4
   status: 0
  success: True
        x: array([1.49999999])

## Consumption and Saving 

We actually solve a max problem 

\begin{equation}
\begin{split}
max \;\; & U = u(c_t) + \beta u(c_{t+1}) \\
s.t. \;\; &  c_t + \frac{c_{t+1}}{1+r_t} = Y_t + \frac{Y_{t+1}}{1+r_t} 
\end{split}
\end{equation}

which is 

\begin{equation}
\begin{split}
max \;\; & U = u(c_t) + \beta u\bigg((1+r_t)Y_t - Y_{t+1} - (1+r_t)c_t \bigg) \\\end{split}
\end{equation}


---

In [41]:
r = 0.05
bet = 1/(1+r)
Y0 = 50
Y1 = 100

def U(c0):
    c1 = Y0*(1+r) + Y1 - (1+r)*c0
    util = np.log(c0) + bet*np.log(c1)
    return util

In [42]:
U(50)

8.297899373035852

In [43]:
U(75)

8.413374775650528

In [46]:
def U2(c0):
    return -1*U(c0)

In [47]:
minimize(U2, 50)

      fun: -8.413443662797203
 hess_inv: array([[2701.01432484]])
      jac: array([0.])
  message: 'Optimization terminated successfully.'
     nfev: 30
      nit: 5
     njev: 10
   status: 0
  success: True
        x: array([74.39034761])